
shared_libs := libcdroid_server
libcdroid_server_src = $(wildcard $(current_dir)/*.cpp) $(wildcard $(current_dir)/*.c)
libcdroid_server_dep = lib/libcutils.so lib/libutils.so
local_cflags = -I$(topdir)/include
local_ldflags =


include $(RULESMK)
