shared_libs := libcdroid_runtime
libcdroid_runtime_src = $(wildcard $(current_dir)/*.cpp) $(wildcard $(current_dir)/*.c)
libcdroid_runtime_dep = lib/libcutils.so lib/libutils.so
local_cflags = -I$(topdir)/include
local_ldflags =


include $(RULESMK)
