progs := handle_test
handle_test_src = $(wildcard $(current_dir)/*.cpp) $(wildcard $(current_dir)/*.c)
local_cflags =
local_ldflags = -lcdroid_server -lcdroid_runtime -lutils -lbinder -llog -lcutils -lcorkscrew -lz -ldl -lpthread -lrt


include $(RULESMK)
